import nodemailer from "nodemailer";

/**
 * Sends a notification email when a new contact form is submitted.
 * @param {Object} data - The form data containing name, email, subject, message
 */
export const sendContactNotification = async (data) => {
  const { name, email, subject, message } = data;

  // Validate SMTP credentials
  const smtpHost = process.env.SMTP_HOST;
  const smtpPort = process.env.SMTP_PORT || 587;
  const smtpUser = process.env.SMTP_USER;
  const smtpPass = process.env.SMTP_PASS;
  const emailTo = process.env.EMAIL_TO || "abdulwahidhadi08@gmail.com";
  const emailFrom = process.env.EMAIL_FROM || "portfolio-contact@example.com";

  if (!smtpUser || !smtpPass) {
    console.log("⚠️ SMTP credentials not fully configured in environment variables (.env).");
    console.log("✉️ Simulated Email Dispatch Log:");
    console.log(`   To: ${emailTo}`);
    console.log(`   From: ${emailFrom}`);
    console.log(`   Subject: New Portfolio Contact: ${subject}`);
    console.log(`   Sender: ${name} <${email}>`);
    console.log(`   Message: ${message}`);
    return { simulated: true, success: true };
  }

  try {
    const transporter = nodemailer.createTransport({
      host: smtpHost,
      port: smtpPort,
      secure: smtpPort == 465, // true for 465, false for others
      auth: {
        user: smtpUser,
        pass: smtpPass,
      },
    });

    const mailOptions = {
      from: `"${name} (via Portfolio)" <${emailFrom}>`,
      to: emailTo,
      replyTo: email,
      subject: `💼 Portfolio Contact: ${subject}`,
      text: `You have received a new contact message from your portfolio website.
      
Name: ${name}
Email: ${email}
Subject: ${subject}

Message:
${message}`,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e0e0e0; border-radius: 10px;">
          <h2 style="color: #3b82f6; border-bottom: 2px solid #3b82f6; padding-bottom: 10px;">New Message from Portfolio</h2>
          <table style="width: 100%; margin-top: 15px; border-collapse: collapse;">
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #4b5563; width: 100px;">Sender:</td>
              <td style="padding: 8px 0; color: #1f2937;">${name}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #4b5563;">Email:</td>
              <td style="padding: 8px 0; color: #1f2937;"><a href="mailto:${email}" style="color: #3b82f6; text-decoration: none;">${email}</a></td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #4b5563;">Subject:</td>
              <td style="padding: 8px 0; color: #1f2937;">${subject}</td>
            </tr>
          </table>
          <div style="margin-top: 20px; padding: 15px; background-color: #f9fafb; border-left: 4px solid #3b82f6; border-radius: 4px;">
            <p style="margin: 0; font-weight: bold; color: #4b5563; margin-bottom: 8px;">Message:</p>
            <p style="margin: 0; color: #1f2937; line-height: 1.6; white-space: pre-wrap;">${message}</p>
          </div>
          <p style="margin-top: 25px; font-size: 11px; color: #9ca3af; text-align: center; border-top: 1px solid #e5e7eb; padding-top: 15px;">
            This email was automatically generated by your portfolio server. You can click "Reply" to respond directly to the sender.
          </p>
        </div>
      `,
    };

    const info = await transporter.sendMail(mailOptions);
    console.log(`✉️ Email notification sent successfully: ${info.messageId}`);
    return { success: true, messageId: info.messageId };
  } catch (error) {
    console.error("❌ Email notification sending failed:", error);
    return { success: false, error: error.message };
  }
};
